create table if not exists public.convertflow_admin_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info' check (level in ('info','success','warning','error')),
  event text not null,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists convertflow_admin_logs_created_idx on public.convertflow_admin_logs(created_at desc);
alter table public.convertflow_admin_logs enable row level security;
