import express from "express";
import { verifyAdminToken } from "./admin.js";
const router=express.Router();
function admin(req,res,next){const a=String(req.headers.authorization||"");const token=a.startsWith("Bearer ")?a.slice(7):"";if(!verifyAdminToken(token))return res.status(401).json({success:false,message:"Unauthorized or expired admin session."});next()}
function cfg(){return {url:String(process.env.SUPABASE_URL||"").replace(/\/$/,""),key:String(process.env.SUPABASE_SERVICE_ROLE_KEY||"")}}
async function sb(url,key,path,options={}){return fetch(`${url}${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,...(options.headers||{})}})}
router.get("/analytics",admin,async(req,res)=>{const {url,key}=cfg();if(!url||!key)return res.status(503).json({success:false,message:"Supabase analytics is not configured."});try{const [keysRes,eventsRes,todayRes,monthRes]=await Promise.all([sb(url,key,"/rest/v1/convertflow_api_keys?select=id,plan,expires_at,revoked_at,usage_count,usage_limit,last_used_at"),sb(url,key,"/rest/v1/convertflow_conversion_events?select=id,source,created_at&order=created_at.desc&limit=1000"),sb(url,key,`/rest/v1/convertflow_conversion_events?created_at=gte.${encodeURIComponent(new Date(Date.now()-86400000).toISOString())}&select=id`),sb(url,key,`/rest/v1/convertflow_conversion_events?created_at=gte.${encodeURIComponent(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString())}&select=id`)]);const keys=await keysRes.json().catch(()=>[]),events=await eventsRes.json().catch(()=>[]),today=await todayRes.json().catch(()=>[]),month=await monthRes.json().catch(()=>[]);return res.json({success:true,keys:{total:keys.length,active:keys.filter(k=>!k.revoked_at&&(!k.expires_at||new Date(k.expires_at)>new Date())).length,expired:keys.filter(k=>k.expires_at&&new Date(k.expires_at)<=new Date()).length,revoked:keys.filter(k=>k.revoked_at).length},conversions:{today:today.length,month:month.length,total:events.length},recent:events.slice(0,20)});}catch(e){return res.status(502).json({success:false,message:e.message})}});
router.get("/api-keys/usage",admin,async(req,res)=>{const {url,key}=cfg();const r=await sb(url,key,"/rest/v1/convertflow_api_keys?select=id,name,plan,usage_count,usage_limit,usage_reset_at,last_used_at&order=usage_count.desc");const data=await r.json().catch(()=>[]);if(!r.ok)return res.status(502).json({success:false,message:"Could not load API usage."});return res.json({success:true,keys:data})});
export default router;
