import express from "express";
import crypto from "crypto";
import { verifyAdminToken } from "./admin.js";

const router = express.Router();
function adminOnly(req,res,next){const a=String(req.headers.authorization||"");const t=a.startsWith("Bearer ")?a.slice(7):"";if(!verifyAdminToken(t))return res.status(401).json({success:false,message:"Unauthorized."});next();}
function sb(){return {url:String(process.env.SUPABASE_URL||"").replace(/\/$/,""),key:String(process.env.SUPABASE_SERVICE_ROLE_KEY||"")};}
function vaultKey(){return crypto.createHash("sha256").update(String(process.env.ADMIN_CONTROL_SECRET||"convertflow-vault")).digest();}
function encrypt(value){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv("aes-256-gcm",vaultKey(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return {encrypted_key:encrypted.toString("base64url"),iv:iv.toString("base64url"),auth_tag:cipher.getAuthTag().toString("base64url")};}
function decrypt(row){const decipher=crypto.createDecipheriv("aes-256-gcm",vaultKey(),Buffer.from(row.iv,"base64url"));decipher.setAuthTag(Buffer.from(row.auth_tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(row.encrypted_key,"base64url")),decipher.final()]).toString("utf8");}
function expiry(plan){if(plan==="permanent")return null;const d=new Date();if(plan==="month")d.setMonth(d.getMonth()+1);else d.setFullYear(d.getFullYear()+1);return d.toISOString();}
function limit(plan){return plan==="month"?1000:plan==="year"?15000:50000;}
async function call(path,options={}){const {url,key}=sb();if(!url||!key)throw new Error("Supabase API licensing is not configured on the backend.");return fetch(`${url}${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,...(options.headers||{})}});}
async function supabaseError(response){const text=await response.text().catch(()=>"");let data=null;try{data=text?JSON.parse(text):null;}catch{}return data?.message||data?.hint||data?.details||text||`HTTP ${response.status}`;}
function cleanError(message){return String(message).replace(/https?:\/\/[^\s]+/g,"[url]").slice(0,500);}
router.post("/",adminOnly,async(req,res)=>{const name=String(req.body?.name||"").trim(),plan=String(req.body?.plan||"").toLowerCase();if(!name||name.length>100)return res.status(400).json({success:false,message:"Enter an API name up to 100 characters."});if(!["month","year","permanent"].includes(plan))return res.status(400).json({success:false,message:"Invalid expiry option."});const {url,key}=sb();if(!url||!key)return res.status(503).json({success:false,message:"Supabase API licensing is not configured on the backend. Check SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Render."});const raw=`cf_live_${crypto.randomBytes(32).toString("base64url")}`,hash=crypto.createHash("sha256").update(raw).digest("hex"),expiresAt=expiry(plan);try{const r=await call("/rest/v1/convertflow_api_keys",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({name,key_hash:hash,key_prefix:raw.slice(0,16),plan,expires_at:expiresAt,usage_count:0,usage_limit:limit(plan),usage_reset_at:expiresAt})});if(!r.ok){const detail=cleanError(await supabaseError(r));console.error("API vault key insert failed:",r.status,detail);return res.status(502).json({success:false,message:`Could not create API key. Database error: ${detail}`});}const rows=await r.json().catch(()=>[]);if(!rows[0]?.id){console.error("API vault key insert returned no row");return res.status(502).json({success:false,message:"Could not create API key. Supabase returned no created record."});}const vault=encrypt(raw);const v=await call("/rest/v1/convertflow_api_key_vault",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({api_key_id:rows[0].id,...vault})});if(!v.ok){const detail=cleanError(await supabaseError(v));console.error("API vault secure insert failed:",v.status,detail);await call(`/rest/v1/convertflow_api_keys?id=eq.${encodeURIComponent(rows[0].id)}`,{method:"DELETE"}).catch(()=>{});return res.status(502).json({success:false,message:`Could not secure the API key. Database error: ${detail}`});}return res.json({success:true,apiKey:raw,name,plan,expiresAt});}catch(e){console.error("API vault create error:",e);return res.status(502).json({success:false,message:cleanError(e.message||"Could not create API key.")})}});
router.get("/",adminOnly,async(req,res)=>{try{await call(`/rest/v1/convertflow_api_keys?expires_at=not.is.null&expires_at=lte.${encodeURIComponent(new Date().toISOString())}`,{method:"DELETE"}).catch(()=>{});const r=await call("/rest/v1/convertflow_api_keys?revoked_at=is.null&order=created_at.desc&select=id,name,key_prefix,plan,expires_at,created_at,last_used_at,usage_count,usage_limit,usage_reset_at");const rows=await r.json().catch(()=>[]);if(!r.ok)return res.status(502).json({success:false,message:`Could not load API keys. Database error: ${cleanError(await supabaseError(r))}`});return res.json({success:true,keys:rows});}catch(e){return res.status(502).json({success:false,message:cleanError(e.message||"Could not load API keys.")})}});
router.post("/:id/reveal",adminOnly,async(req,res)=>{try{const r=await call(`/rest/v1/convertflow_api_key_vault?api_key_id=eq.${encodeURIComponent(req.params.id)}&select=encrypted_key,iv,auth_tag`);const rows=await r.json().catch(()=>[]);if(!r.ok||!rows[0])return res.status(404).json({success:false,message:"This key was created before secure key reveal was enabled. Create a new key to use the eye button."});return res.json({success:true,apiKey:decrypt(rows[0])});}catch(e){return res.status(500).json({success:false,message:"Could not reveal this API key."})}});
router.post("/:id/renew",adminOnly,async(req,res)=>{const plan=String(req.body?.plan||"").toLowerCase();if(!["month","year","permanent"].includes(plan))return res.status(400).json({success:false,message:"Invalid renewal plan."});try{const expiresAt=expiry(plan);const r=await call(`/rest/v1/convertflow_api_keys?id=eq.${encodeURIComponent(req.params.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan,expires_at:expiresAt,usage_limit:limit(plan),usage_count:0,usage_reset_at:expiresAt||null})});if(!r.ok)return res.status(502).json({success:false,message:`Could not renew API key. Database error: ${cleanError(await supabaseError(r))}`});return res.json({success:true,expiresAt,plan});}catch(e){return res.status(502).json({success:false,message:cleanError(e.message)})}});
router.delete("/:id",adminOnly,async(req,res)=>{try{const r=await call(`/rest/v1/convertflow_api_keys?id=eq.${encodeURIComponent(req.params.id)}`,{method:"DELETE"});if(!r.ok)return res.status(502).json({success:false,message:`Could not revoke API key. Database error: ${cleanError(await supabaseError(r))}`});return res.json({success:true});}catch(e){return res.status(502).json({success:false,message:cleanError(e.message)})}});
export default router;
