import express from "express";
import multer from "multer";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import sharp from "sharp";
import ffmpegPath from "ffmpeg-static";
import { execFile } from "child_process";
import { promisify } from "util";
import { optionalApiKey } from "../middleware/optionalApiKey.js";
const router=express.Router();
const execFileAsync=promisify(execFile);
const tempDirectory=path.resolve("temp");
if(!fs.existsSync(tempDirectory))fs.mkdirSync(tempDirectory,{recursive:true});
const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,tempDirectory),filename:(_r,f,cb)=>cb(null,`${crypto.randomUUID()}${path.extname(f.originalname)}`)});
const upload=multer({storage,limits:{fileSize:500*1024*1024}});
function cleanup(...files){files.flat().forEach(f=>{if(f&&fs.existsSync(f)){try{fs.unlinkSync(f)}catch{}}})}
function safeName(n){return String(n||"download").replace(/[<>:"/\\|?*\x00-\x1F]/g,"_").replace(/\.\.+/g,"_").slice(0,180)||"download"}
function send(res,input,output,name){if(!fs.existsSync(output))throw new Error("The processing tool did not create an output file.");res.download(output,safeName(name),e=>{cleanup(input,output);if(e)console.error("tool download",e)})}
function requireFile(req){if(!req.file){const e=new Error("No file was uploaded.");e.status=400;throw e}}
function extFormat(format){const f=String(format||"webp").toLowerCase();return ["jpg","jpeg","png","webp","avif"].includes(f)?f:"webp"}
function ffmpegArgs(input,output,args=[]){return ["-hide_banner","-loglevel","error","-y","-i",input,...args,output]}
router.post("/image-crop",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const m=await sharp(req.file.path).metadata();const w=Math.max(1,Math.min(Number(req.body.width)||800,m.width||800));const h=Math.max(1,Math.min(Number(req.body.height)||600,m.height||600));const x=Math.max(0,Math.min(Number(req.body.x)||0,(m.width||w)-w));const y=Math.max(0,Math.min(Number(req.body.y)||0,(m.height||h)-h));out=path.join(tempDirectory,`${crypto.randomUUID()}-crop.png`);await sharp(req.file.path).rotate().extract({left:x,top:y,width:w,height:h}).png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-cropped.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image crop failed."})}});
router.post("/image-optimize",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const format=extFormat(req.body.format),q=Math.max(20,Math.min(100,Number(req.body.quality)||82));out=path.join(tempDirectory,`${crypto.randomUUID()}-optimized.${format}`);let p=sharp(req.file.path).rotate();p=format==="jpg"||format==="jpeg"?p.jpeg({quality:q,mozjpeg:true}):format==="png"?p.png({quality:q,compressionLevel:9}):format==="avif"?p.avif({quality:q}):p.webp({quality:q});await p.toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-optimized.${format}`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image optimization failed."})}});
router.post("/image-metadata-remove",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);out=path.join(tempDirectory,`${crypto.randomUUID()}-clean.png`);await sharp(req.file.path).rotate().png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-metadata-removed.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Metadata removal failed."})}});
router.post("/image-convert",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const format=extFormat(req.body.format);out=path.join(tempDirectory,`${crypto.randomUUID()}-converted.${format}`);let p=sharp(req.file.path).rotate();p=format==="jpg"||format==="jpeg"?p.flatten({background:"white"}).jpeg({quality:92,mozjpeg:true}):format==="png"?p.png():format==="avif"?p.avif({quality:90}):p.webp({quality:90});await p.toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}.${format}`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image conversion failed."})}});
router.post("/image-resize",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const w=Math.max(1,Math.min(10000,Number(req.body.width)||1920));const h=Math.max(1,Math.min(10000,Number(req.body.height)||1080));const keep=String(req.body.keepAspect||"true")!=="false";out=path.join(tempDirectory,`${crypto.randomUUID()}-resize.png`);await sharp(req.file.path).rotate().resize({width:w,height:h,fit:keep?"inside":"fill"}).png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-${w}x${h}.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image resizing failed."})}});
router.post("/image-adjust",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const brightness=Math.max(-100,Math.min(100,Number(req.body.brightness)||0));const saturation=Math.max(-100,Math.min(100,Number(req.body.saturation)||0));const sharpness=Math.max(0,Math.min(5,Number(req.body.sharpness)||0));out=path.join(tempDirectory,`${crypto.randomUUID()}-adjusted.png`);let p=sharp(req.file.path).rotate().modulate({brightness:1+brightness/100,saturation:1+saturation/100});if(sharpness)p=p.sharpen({sigma:sharpness});await p.png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-adjusted.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image adjustment failed."})}});
router.post("/image-watermark",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const text=String(req.body.text||"ConvertFlow").replace(/[<>&"']/g," ").slice(0,100);out=path.join(tempDirectory,`${crypto.randomUUID()}-watermark.png`);const svg=`<svg width="1200" height="180"><style>text{font-family:Arial,sans-serif;font-size:48px;font-weight:700;fill:white;stroke:black;stroke-width:2px;paint-order:stroke;}</style><text x="1140" y="115" text-anchor="end">${text}</text></svg>`;await sharp(req.file.path).rotate().composite([{input:Buffer.from(svg),gravity:"southeast"}]).png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-watermarked.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Watermark failed."})}});
router.post("/image-enhance",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);out=path.join(tempDirectory,`${crypto.randomUUID()}-enhanced.png`);await sharp(req.file.path).rotate().normalize().sharpen({sigma:1.1}).png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-enhanced.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Image enhancement failed."})}});
router.post("/image-background-remover",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const {data,info}=await sharp(req.file.path).rotate().ensureAlpha().raw().toBuffer({resolveWithObject:true});const bg=[data[0],data[1],data[2]];const threshold=Math.max(5,Math.min(120,Number(req.body.threshold)||35));for(let i=0;i<data.length;i+=4){const d=Math.sqrt((data[i]-bg[0])**2+(data[i+1]-bg[1])**2+(data[i+2]-bg[2])**2);if(d<threshold)data[i+3]=0}out=path.join(tempDirectory,`${crypto.randomUUID()}-background.png`);await sharp(data,{raw:info}).png().toFile(out);return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-no-background.png`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:e.message||"Background removal failed."})}});
function video(route,argsBuilder,name,timeout=300000){router.post(route,optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);out=path.join(tempDirectory,`${crypto.randomUUID()}-${name}`);await execFileAsync(ffmpegPath,ffmpegArgs(req.file.path,out,argsBuilder(req)),{timeout,maxBuffer:4*1024*1024});return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-${name}`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:String(e?.stderr||e?.message||"Media processing failed.")})}})}
video("/video-compress",r=>{const q={low:32,medium:28,high:23}[String(r.body.quality||"medium")]||28;const a=["-c:v","libx264","-crf",String(q),"-preset","veryfast","-c:a","aac","-b:a","128k","-movflags","+faststart"];if(["1080p","720p","480p"].includes(r.body.resolution))a.push("-vf",`scale=-2:${String(r.body.resolution).replace("p","")}`);return a},"compressed.mp4");
video("/video-resolution",r=>["-vf",`scale=-2:${({"4k":2160,"1440p":1440,"1080p":1080,"720p":720,"480p":480}[String(r.body.resolution||"1080p").toLowerCase()]||1080)}:flags=lanczos","-c:v","libx264","-preset","veryfast","-c:a","aac","-movflags","+faststart"],"resolution.mp4");
video("/video-framerate",r=>["-r",String(Math.max(1,Math.min(120,Number(r.body.fps)||30))),"-c:v","libx264","-preset","veryfast","-c:a","aac","-movflags","+faststart"],"fps.mp4");
video("/video-mute",()=>["-c:v","copy","-an"],"muted.mp4");
video("/video-speed",r=>["-filter_complex",`[0:v]setpts=${(1/(Number(r.body.speed)||1)).toFixed(4)}*PTS[v];[0:a]atempo=${Math.max(.5,Math.min(2,Number(r.body.speed)||1))}[a]`,"-map","[v]","-map","[a]?","-c:v","libx264","-preset","veryfast","-c:a","aac"],"speed.mp4");
video("/video-thumbnail",r=>["-ss",String(Math.max(0,Number(r.body.time)||1)),"-frames:v","1","-q:v","2"],"thumbnail.jpg",120000);
video("/gif",r=>["-vf",`fps=${Math.max(1,Math.min(30,Number(r.body.fps)||12))},scale=720:-1:flags=lanczos`],"gif.gif");
router.post("/audio-extract",optionalApiKey,upload.single("file"),async(req,res)=>{let out;try{requireFile(req);const f=String(req.body.format||"mp3").toLowerCase();const ext=["mp3","wav","aac","flac","m4a","ogg"].includes(f)?f:"mp3";out=path.join(tempDirectory,`${crypto.randomUUID()}-audio.${ext}`);const codec=ext==="wav"?["-c:a","pcm_s16le"]:ext==="flac"?["-c:a","flac"]:ext==="ogg"?["-c:a","libvorbis","-q:a","5"]:ext==="aac"?["-c:a","aac","-b:a","192k"]:["-c:a","libmp3lame","-b:a","192k"];if(ext==="m4a")codec.splice(0,codec.length,"-c:a","aac","-b:a","192k");await execFileAsync(ffmpegPath,ffmpegArgs(req.file.path,out,["-vn",...codec]),{timeout:300000,maxBuffer:4*1024*1024});return send(res,req.file.path,out,`${path.parse(req.file.originalname).name}-audio.${ext}`)}catch(e){cleanup(req.file?.path,out);return res.status(e.status||500).json({success:false,message:String(e?.stderr||e?.message||"Audio extraction failed.")})}});
export default router;
