import express from "express";
import { verifyAdminToken, sb, writeLog } from "./admin.js";
const router=express.Router();
const DEFAULT={analyzer:true,duplicates:true,rename:true,split:true,merge:true,contact:true,palette:true,blur:true,pixelate:true,qr:true,scan:true,barcode:true,beautify:true,favicon:true,webp:true,command:true,"ai-image":false,tts:true};
function requireAdmin(req,res,next){const a=String(req.headers.authorization||"");const token=a.startsWith("Bearer ")?a.slice(7):"";if(!verifyAdminToken(token))return res.status(401).json({success:false,message:"Unauthorized or expired admin session."});next()}
async function getTools(){const r=await sb("/rest/v1/site_control?id=eq.1&select=advanced_tools_enabled");const data=await r.json().catch(()=>[]);if(!r.ok||!data[0])throw Object.assign(new Error("Could not read Advanced Tool settings."),{statusCode:502});return {...DEFAULT,...(data[0].advanced_tools_enabled||{})}}
router.get("/status",async(req,res)=>{try{return res.json({success:true,tools:await getTools()})}catch(e){return res.status(e.statusCode||502).json({success:false,message:e.message})}});
router.patch("/:id",requireAdmin,async(req,res)=>{try{const id=String(req.params.id);if(!Object.prototype.hasOwnProperty.call(DEFAULT,id))return res.status(400).json({success:false,message:"Unknown Advanced Tool."});const tools=await getTools();tools[id]=req.body?.enabled===true;const r=await sb("/rest/v1/site_control?id=eq.1",{method:"PATCH",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({advanced_tools_enabled:tools,updated_at:new Date().toISOString()})});if(!r.ok)throw Object.assign(new Error(`Supabase returned HTTP ${r.status}.`),{statusCode:502});await writeLog("success","advanced-tool.changed",`Advanced tool ${id} ${tools[id]?"enabled":"disabled"}`,{id,enabled:tools[id]});return res.json({success:true,tools})}catch(e){return res.status(e.statusCode||502).json({success:false,message:e.message})}});
export default router;
