import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, MessageSquareText, RefreshCw, Search, Star } from "lucide-react";
import { useNavigate } from "react-router-dom";

const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const card={border:"1px solid rgba(148,163,184,.16)",borderRadius:22,background:"linear-gradient(180deg,rgba(17,25,39,.96),rgba(8,12,20,.96))",boxShadow:"0 20px 60px rgba(0,0,0,.22)"};
async function request(path,token){const r=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||`Request failed (${r.status})`);return d;}

export default function AdminFeedback(){
 const navigate=useNavigate();
 const token=sessionStorage.getItem("convertflow_admin_token")||"";
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[rating,setRating]=useState("all");
 const load=useCallback(async()=>{if(!token){navigate("/admin",{replace:true});return;}setLoading(true);try{const d=await request("/admin/feedback?limit=500",token);setItems(d.feedback||[]);setError("");}catch(e){setError(e.message);if(/unauthorized|expired/i.test(e.message))navigate("/admin",{replace:true});}finally{setLoading(false);}},[navigate,token]);
 useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>items.filter(x=>(rating==="all"||String(x.rating)===rating)&&(!query||`${x.message||""} ${x.page||""}`.toLowerCase().includes(query.toLowerCase()))),[items,query,rating]);
 const average=items.length?(items.reduce((sum,x)=>sum+Number(x.rating||0),0)/items.length).toFixed(1):"0.0";
 return <main style={{minHeight:"100vh",padding:"28px 18px 70px",background:"radial-gradient(circle at 10% 0%,#18243b 0,#080c14 38%,#04060a 100%)",color:"#f8fafc"}}><section style={{width:"min(1200px,100%)",margin:"0 auto"}}>
  <header style={{...card,padding:"20px 22px",display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,marginBottom:18,flexWrap:"wrap"}}>
   <div style={{display:"flex",alignItems:"center",gap:13}}><div style={{width:46,height:46,borderRadius:14,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#22c55e,#0ea5e9)"}}><MessageSquareText/></div><div><small style={{opacity:.45,fontWeight:900,letterSpacing:2}}>CONVERTFLOW / ADMIN</small><h1 style={{margin:"3px 0",fontSize:26}}>Customer Feedback</h1><span style={{opacity:.5,fontSize:12}}>Read what visitors are saying about ConvertFlow.</span></div></div>
   <div style={{display:"flex",gap:8}}><button onClick={()=>navigate("/admin/control")} style={{border:"1px solid rgba(148,163,184,.22)",borderRadius:12,padding:"10px 14px",background:"rgba(255,255,255,.05)",color:"inherit",fontWeight:800,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:7}}><ArrowLeft size={16}/> Admin Control</button><button onClick={load} style={{border:"1px solid rgba(148,163,184,.22)",borderRadius:12,padding:"10px 14px",background:"rgba(255,255,255,.05)",color:"inherit",fontWeight:800,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:7}}><RefreshCw size={16}/> Refresh</button></div>
  </header>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:16}}><div style={{...card,padding:18}}><small style={{opacity:.5}}>TOTAL FEEDBACK</small><strong style={{display:"block",fontSize:28,marginTop:8}}>{items.length}</strong></div><div style={{...card,padding:18}}><small style={{opacity:.5}}>AVERAGE RATING</small><strong style={{display:"block",fontSize:28,marginTop:8,display:"flex",alignItems:"center",gap:7}}>{average}<Star size={20} fill="currentColor"/></strong></div></div>
  <section style={{...card,padding:18}}><div style={{display:"flex",gap:9,flexWrap:"wrap",marginBottom:16}}><div style={{flex:"1 1 260px",position:"relative"}}><Search size={17} style={{position:"absolute",left:13,top:12,opacity:.45}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search feedback..." style={{width:"100%",boxSizing:"border-box",padding:"11px 12px 11px 40px",borderRadius:12,border:"1px solid rgba(148,163,184,.2)",background:"rgba(255,255,255,.04)",color:"inherit"}}/></div>{["all","5","4","3","2","1"].map(x=><button key={x} onClick={()=>setRating(x)} style={{border:"1px solid rgba(148,163,184,.18)",borderRadius:11,padding:"9px 12px",background:rating===x?"rgba(14,165,233,.16)":"rgba(255,255,255,.04)",color:"inherit",fontWeight:800,cursor:"pointer"}}>{x==="all"?"All":`${x} ★`}</button>)}</div>
   {loading?<p style={{opacity:.55}}>Loading feedback...</p>:error?<p style={{color:"#fca5a5"}}>{error}</p>:filtered.length===0?<div style={{padding:"45px 20px",textAlign:"center",opacity:.5}}>No feedback matches your filters.</div>:<div style={{display:"grid",gap:10}}>{filtered.map(item=><article key={item.id} style={{padding:18,borderRadius:17,border:"1px solid rgba(148,163,184,.12)",background:"rgba(255,255,255,.025)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",gap:3}}>{Array.from({length:5},(_,i)=><Star key={i} size={16} fill={i<Number(item.rating)?"currentColor":"none"} style={{opacity:i<Number(item.rating)?1:.25}}/>)}</div><small style={{opacity:.45}}>{item.created_at?new Date(item.created_at).toLocaleString():""}</small></div><p style={{fontSize:15,lineHeight:1.65,margin:"13px 0 8px",whiteSpace:"pre-wrap"}}>{item.message}</p>{item.page&&<small style={{opacity:.45}}>Page: {item.page}</small>}</article>)}</div>}
  </section>
 </section></main>;
}
