import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity, AlertTriangle, Bell, CheckCircle2, Clock3, Cpu, Database, Gauge, KeyRound, Megaphone, RefreshCw, Server, ShieldAlert, SlidersHorizontal, ToggleLeft, Wrench, XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import "./adminOperations.css";
const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
async function req(path,token,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||`Request failed (${r.status})`);return d}
const Toggle=({on,onChange,label})=><button className={`ao-toggle ${on?'on':''}`} onClick={()=>onChange(!on)} aria-label={label}><i/></button>;
export default function AdminOperations(){const navigate=useNavigate(),token=sessionStorage.getItem("convertflow_admin_token")||"";const[health,setHealth]=useState(null),[analytics,setAnalytics]=useState(null),[logs,setLogs]=useState([]),[keys,setKeys]=useState([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[flags,setFlags]=useState(()=>JSON.parse(localStorage.getItem("cf_admin_flags")||'{}')),[announcement,setAnnouncement]=useState(()=>localStorage.getItem("cf_admin_announcement")||"");
 const load=useCallback(async()=>{if(!token)return navigate('/admin');setLoading(true);try{const[h,a,l,k]=await Promise.all([fetch(`${API}/health`).then(r=>r.json()),req('/admin/analytics',token),req('/admin/logs?limit=200',token),req('/admin/api-vault',token).catch(()=>({keys:[]}))]);setHealth(h);setAnalytics(a);setLogs(l.logs||[]);setKeys(k.keys||[]);setMessage("")}catch(e){setMessage(e.message)}finally{setLoading(false)}},[token,navigate]);useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);
 const errors=useMemo(()=>logs.filter(x=>x.level==='error'),[logs]);const warnings=useMemo(()=>logs.filter(x=>x.level==='warning'),[logs]);const tools=['Image Upscaler','Video Compressor','GIF Maker','Image Enhancer','Background Remover','Audio Extractor'];
 function flag(name,value){const next={...flags,[name]:value};setFlags(next);localStorage.setItem('cf_admin_flags',JSON.stringify(next));setMessage(`${name} ${value?'enabled':'disabled'}.`)}
 function saveAnnouncement(){localStorage.setItem('cf_admin_announcement',announcement);setMessage('Announcement saved for this admin browser. Connect it to your backend announcement table when you want it global.')}
 return <main className="ao-page"><div className="ao-shell"><header className="ao-head"><div><span>CONVERTFLOW / ADMIN OPERATIONS</span><h1>Operations Center</h1><p>System health, failures, API activity, tools and security events in one place.</p></div><div><button className="ao-btn" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="ao-btn" onClick={()=>navigate('/admin/control')}>Control panel</button></div></header>{message&&<div className="ao-message">{message}</div>}
 <section className="ao-stats"><article><Server/><small>BACKEND</small><strong className={health?.success?'good':'bad'}>{health?.success?'ONLINE':'ERROR'}</strong><span>{health?.version||'Health endpoint'}</span></article><article><Activity/><small>CONVERSIONS TODAY</small><strong>{analytics?.conversions?.today??0}</strong><span>Live analytics</span></article><article><KeyRound/><small>ACTIVE API KEYS</small><strong>{analytics?.keys?.active??keys.length}</strong><span>{analytics?.keys?.expired??0} expired</span></article><article><ShieldAlert/><small>ERRORS</small><strong className={errors.length?'bad':'good'}>{errors.length}</strong><span>{warnings.length} warnings</span></article></section>
 <div className="ao-grid"><section className="ao-card"><div className="ao-title"><div><span>01 / SYSTEM MONITOR</span><h2>Live infrastructure</h2></div><Gauge/></div><div className="ao-health"><div><Cpu/><b>API response</b><span>{health?.success?'Operational':'Unavailable'}</span></div><div><Database/><b>Database</b><span>{analytics?'Reachable through admin API':'Unknown'}</span></div><div><Server/><b>Render service</b><span>Process stays online when frontend access is disabled</span></div></div></section>
 <section className="ao-card"><div className="ao-title"><div><span>02 / FAILED CONVERSIONS</span><h2>Problems to investigate</h2></div><AlertTriangle/></div><div className="ao-list">{errors.slice(0,8).map(x=><div key={x.id}><XCircle/><div><b>{x.event}</b><span>{x.message}</span><small>{new Date(x.created_at).toLocaleString()}</small></div></div>)}{!errors.length&&<div className="ao-empty"><CheckCircle2/> No recorded errors.</div>}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>03 / TOOL CONTROLS</span><h2>Feature switches</h2></div><SlidersHorizontal/></div><p className="ao-note">These switches are safe browser-side admin flags. Public enforcement should be connected to the backend before using them as access controls.</p><div className="ao-switches">{tools.map(t=><div key={t}><span>{t}</span><Toggle label={t} on={flags[t]!==false} onChange={v=>flag(t,v)}/></div>)}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>04 / API OPERATIONS</span><h2>API activity</h2></div><KeyRound/></div><div className="ao-key-grid">{keys.slice(0,8).map(k=><div key={k.id}><b>{k.name}</b><span>{k.key_prefix}••••</span><small>{k.plan} · {k.usage_count||0} requests</small></div>)}{!keys.length&&<div className="ao-empty">No API keys returned.</div>}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>05 / MAINTENANCE SCHEDULER</span><h2>Schedule window</h2></div><Clock3/></div><p className="ao-note">Prepare the scheduler UI here. The existing site-mode controls remain the authoritative switch.</p><div className="ao-schedule"><label>Start<input type="datetime-local"/></label><label>End<input type="datetime-local"/></label><button className="ao-btn" onClick={()=>setMessage('Schedule prepared. Use the Control panel to apply maintenance mode.')}>Prepare schedule</button></div></section>
 <section className="ao-card"><div className="ao-title"><div><span>06 / ANNOUNCEMENTS</span><h2>Website announcement</h2></div><Megaphone/></div><textarea value={announcement} onChange={e=>setAnnouncement(e.target.value)} placeholder="Example: New 8K image upscaler is now available."/><button className="ao-btn primary" onClick={saveAnnouncement}><Bell size={16}/> Save announcement</button></section>
 <section className="ao-card"><div className="ao-title"><div><span>07 / FEATURE FLAGS</span><h2>Experimental releases</h2></div><ToggleLeft/></div>{['New tools UI','Advanced utilities','API v2','Fast image pipeline','New video pipeline'].map(x=><div className="ao-flag" key={x}><span>{x}</span><Toggle label={x} on={flags[x]===true} onChange={v=>flag(x,v)}/></div>)}</section>
 <section className="ao-card ao-wide"><div className="ao-title"><div><span>08 / AUDIT LOG</span><h2>Website errors and security events</h2></div><ShieldAlert/></div><div className="ao-log">{logs.slice(0,40).map(x=><div key={x.id} className={x.level}><span>{x.level.toUpperCase()}</span><b>{x.event}</b><p>{x.message}</p><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div></section>
 </div></div></main>}
