import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity, AlertTriangle, Bell, CheckCircle2, Clock3, Cpu, Database, Gauge, KeyRound, Megaphone, RefreshCw, Server, SlidersHorizontal, ToggleLeft, XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import "./adminOperations.css";
const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const localDateTime=iso=>{if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
async function req(path,token,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||`Request failed (${r.status})`);return d}
const Toggle=({on,onChange,label})=><button className={`ao-toggle ${on?'on':''}`} onClick={()=>onChange(!on)} aria-label={label}><i/></button>;
export default function AdminOperations(){const navigate=useNavigate(),token=sessionStorage.getItem("convertflow_admin_token")||"";const[health,setHealth]=useState(null),[analytics,setAnalytics]=useState(null),[logs,setLogs]=useState([]),[keys,setKeys]=useState([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[flags,setFlags]=useState(()=>JSON.parse(localStorage.getItem("cf_admin_flags")||'{}')),[announcement,setAnnouncement]=useState({enabled:false,title:"",message:"",type:"info",expiresAt:""});
 const load=useCallback(async()=>{if(!token)return navigate('/admin');setLoading(true);try{const[h,a,l,k,an]=await Promise.all([fetch(`${API}/health`).then(r=>r.json()),req('/admin/analytics',token),req('/admin/logs?limit=200',token),req('/admin/api-vault',token).catch(()=>({keys:[]})),fetch(`${API}/announcement`,{cache:'no-store'}).then(r=>r.json()).catch(()=>null)]);setHealth(h);setAnalytics(a);setLogs(l.logs||[]);setKeys(k.keys||[]);if(an?.announcement)setAnnouncement({enabled:!!an.announcement.enabled,title:an.announcement.title||"",message:an.announcement.message||"",type:an.announcement.type||"info",expiresAt:localDateTime(an.announcement.expires_at)});setMessage("")}catch(e){setMessage(e.message)}finally{setLoading(false)}},[token,navigate]);useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);
 const errors=useMemo(()=>logs.filter(x=>x.level==='error'),[logs]);const warnings=useMemo(()=>logs.filter(x=>x.level==='warning'),[logs]);const tools=['Image Upscaler','Video Compressor','GIF Maker','Image Enhancer','Background Remover','Audio Extractor'];
 function flag(name,value){const next={...flags,[name]:value};setFlags(next);localStorage.setItem('cf_admin_flags',JSON.stringify(next));setMessage(`${name} ${value?'enabled':'disabled'}.`)}
 async function saveAnnouncement(){try{if(announcement.enabled&&announcement.expiresAt&&new Date(announcement.expiresAt).getTime()<=Date.now())return setMessage('Choose a future expiration time.');const payload={...announcement,expiresAt:announcement.expiresAt?new Date(announcement.expiresAt).toISOString():null};const d=await req('/announcement',token,{method:'PUT',body:JSON.stringify(payload)});setAnnouncement(a=>({...a,expiresAt:localDateTime(d.announcement?.expires_at)}));setMessage(announcement.enabled?'Announcement published to the public website.':'Announcement disabled.')}catch(e){setMessage(e.message)}}
 return <main className="ao-page"><div className="ao-shell"><header className="ao-head"><div><span>CONVERTFLOW / ADMIN OPERATIONS</span><h1>Operations Center</h1><p>System health, failures, API activity and tools in one place.</p></div><div><button className="ao-btn" onClick={load}><RefreshCw size={16}/> {loading?'Refreshing':'Refresh'}</button><button className="ao-btn" onClick={()=>navigate('/admin/control')}>Control panel</button></div></header>{message&&<div className="ao-message">{message}</div>}
 <section className="ao-stats"><article><Server/><small>BACKEND</small><strong className={health?.success?'good':'bad'}>{health?.success?'ONLINE':'ERROR'}</strong><span>{health?.version||'Health endpoint'}</span></article><article><Activity/><small>CONVERSIONS TODAY</small><strong>{analytics?.conversions?.today??0}</strong><span>Live analytics</span></article><article><KeyRound/><small>ACTIVE API KEYS</small><strong>{analytics?.keys?.active??keys.length}</strong><span>{analytics?.keys?.expired??0} expired</span></article><article><AlertTriangle/><small>RECORDED ERRORS</small><strong className={errors.length?'bad':'good'}>{errors.length}</strong><span>{warnings.length} warnings</span></article></section>
 <div className="ao-grid"><section className="ao-card"><div className="ao-title"><div><span>01 / SYSTEM MONITOR</span><h2>Live infrastructure</h2></div><Gauge/></div><div className="ao-health"><div><Cpu/><b>API response</b><span>{health?.success?'Operational':'Unavailable'}</span></div><div><Database/><b>Database</b><span>{analytics?'Reachable through admin API':'Unknown'}</span></div><div><Server/><b>Render service</b><span>Process stays online when frontend access is disabled</span></div></div></section>
 <section className="ao-card"><div className="ao-title"><div><span>02 / FAILED CONVERSIONS</span><h2>Problems to investigate</h2></div><AlertTriangle/></div><div className="ao-list">{errors.slice(0,8).map(x=><div key={x.id}><XCircle/><div><b>{x.event}</b><span>{x.message}</span><small>{new Date(x.created_at).toLocaleString()}</small></div></div>)}{!errors.length&&<div className="ao-empty"><CheckCircle2/> No recorded errors.</div>}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>03 / TOOL CONTROLS</span><h2>Feature switches</h2></div><SlidersHorizontal/></div><p className="ao-note">These switches are safe browser-side admin flags.</p><div className="ao-switches">{tools.map(t=><div key={t}><span>{t}</span><Toggle label={t} on={flags[t]!==false} onChange={v=>flag(t,v)}/></div>)}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>04 / API OPERATIONS</span><h2>API activity</h2></div><KeyRound/></div><div className="ao-key-grid">{keys.slice(0,8).map(k=><div key={k.id}><b>{k.name}</b><span>{k.key_prefix}••••</span><small>{k.plan} · {k.usage_count||0} requests</small></div>)}{!keys.length&&<div className="ao-empty">No API keys returned.</div>}</div></section>
 <section className="ao-card"><div className="ao-title"><div><span>05 / MAINTENANCE SCHEDULER</span><h2>Schedule window</h2></div><Clock3/></div><p className="ao-note">Prepare the scheduler UI here. The existing site-mode controls remain the authoritative switch.</p><div className="ao-schedule"><label>Start<input type="datetime-local"/></label><label>End<input type="datetime-local"/></label><button className="ao-btn" onClick={()=>setMessage('Schedule prepared. Use the Control panel to apply maintenance mode.')}>Prepare schedule</button></div></section>
 <section className="ao-card"><div className="ao-title"><div><span>06 / PUBLIC ANNOUNCEMENT</span><h2>Website announcement</h2></div><Megaphone/></div><div className="ao-form-grid"><label>Title<input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})} placeholder="New feature available"/></label><label>Type<select value={announcement.type} onChange={e=>setAnnouncement({...announcement,type:e.target.value})}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="danger">Important</option></select></label></div><textarea value={announcement.message} onChange={e=>setAnnouncement({...announcement,message:e.target.value})} placeholder="Write the announcement users should see..."/><label className="ao-check"><input type="checkbox" checked={announcement.enabled} onChange={e=>setAnnouncement({...announcement,enabled:e.target.checked})}/> Publish to the public website</label><label>Automatically remove after<input type="datetime-local" value={announcement.expiresAt} onChange={e=>setAnnouncement({...announcement,expiresAt:e.target.value})}/></label><p className="ao-note">Only one announcement is stored. Publishing another replaces the old one. At the expiration time it is automatically disabled.</p><button className="ao-btn primary" onClick={saveAnnouncement}><Bell size={16}/> Save announcement</button></section>
 <section className="ao-card"><div className="ao-title"><div><span>07 / FEATURE FLAGS</span><h2>Experimental releases</h2></div><ToggleLeft/></div>{['New tools UI','Advanced utilities','API v2','Fast image pipeline','New video pipeline'].map(x=><div className="ao-flag" key={x}><span>{x}</span><Toggle label={x} on={flags[x]===true} onChange={v=>flag(x,v)}/></div>)}</section>
 </div></div></main>}
