import { useState } from "react";
import { Code2, Copy, FileUp, Play, ShieldCheck } from "lucide-react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./apiPlayground.css";

const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
export default function ApiPlayground(){
 const[key,setKey]=useState(""),[file,setFile]=useState(null),[tool,setTool]=useState("image-optimize"),[format,setFormat]=useState("webp"),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function run(){if(!key.trim())return setError("Enter an API key first.");if(!file)return setError("Choose a file first.");setBusy(true);setError("");setResult(null);const form=new FormData();form.append("file",file);if(tool==="image-optimize"||tool==="image-convert"||tool==="audio-extract")form.append("format",format);if(tool==="image-optimize")form.append("quality","82");try{const res=await fetch(`${API}/tools/${tool}`,{method:"POST",headers:{"x-convertflow-api-key":key.trim()},body:form});if(!res.ok){let msg=`Request failed (${res.status})`;try{msg=(await res.json()).message||msg}catch{}throw new Error(msg)}const blob=await res.blob();const url=URL.createObjectURL(blob);setResult({url,name:`convertflow-${file.name.replace(/\.[^.]+$/i,"")}.${format}`})}catch(e){setError(e.message||"The API request failed.")}finally{setBusy(false)}}
 const curl=`curl -X POST "${API}/tools/${tool}" -H "x-convertflow-api-key: YOUR_API_KEY" -F "file=@your-file"`;
 return <div className="app api-playground"><Header/><main className="pg-shell"><section className="pg-hero"><span className="section-label">DEVELOPER PLAYGROUND</span><h1>Test the ConvertFlow API.</h1><p>Use a temporary API key in your browser, upload a file, run a real request and download the response. The key is not saved to localStorage.</p></section><section className="pg-panel"><div className="pg-step"><div className="pg-num">01</div><div><h2>API key</h2><p>Your key stays in this page session.</p><div className="pg-key"><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="cf_..." autoComplete="off"/><ShieldCheck size={17}/></div></div></div><div className="pg-step"><div className="pg-num">02</div><div><h2>Endpoint</h2><p>Choose what you want to test.</p><select className="pg-select" value={tool} onChange={e=>setTool(e.target.value)}><option value="image-optimize">Image optimizer</option><option value="image-convert">Image format converter</option><option value="image-resize">Image resizer</option><option value="image-metadata-remove">Metadata remover</option><option value="video-compress">Video compressor</option><option value="video-resolution">Video resolution</option><option value="video-thumbnail">Video thumbnail</option><option value="audio-extract">Audio extractor</option></select>{["image-optimize","image-convert","audio-extract"].includes(tool)&&<select className="pg-select" value={format} onChange={e=>setFormat(e.target.value)}>{tool==="audio-extract"?<><option>mp3</option><option>wav</option><option>aac</option><option>flac</option><option>m4a</option><option>ogg</option></>:<><option>webp</option><option>jpg</option><option>png</option><option>avif</option></>}</select>}</div></div><div className="pg-step"><div className="pg-num">03</div><div><h2>Upload</h2><p>The selected file is sent directly to the API.</p><label className="pg-upload"><FileUp size={21}/><span>{file?file.name:"Choose a file"}</span><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="pg-run" disabled={busy} onClick={run}><Play size={16}/>{busy?"Running...":"Run API request"}</button>{error&&<p className="pg-error">{error}</p>}</div></div>{result&&<div className="pg-result"><div><span>200 OK</span><strong>Response ready</strong></div><a href={result.url} download={result.name}>Download response</a></div>}</section><section className="pg-code"><div><Code2 size={18}/><strong>cURL example</strong><button onClick={()=>navigator.clipboard?.writeText(curl)}><Copy size={14}/> Copy</button></div><pre>{curl}</pre></section></main><Footer/></div>;
}
