import { useEffect,useState } from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./phonepeDonate.css";
const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const AMOUNTS=[5,10,25,50,100];
export default function Donate(){
 const[name,setName]=useState(()=>localStorage.getItem("convertflow_donor_name")||"");
 const[amount,setAmount]=useState("50");
 const[busy,setBusy]=useState(false);
 const[result,setResult]=useState("");
 const[error,setError]=useState("");
 const[supporters,setSupporters]=useState([]);
 useEffect(()=>{fetch(`${API}/supporters`).then(r=>r.ok?r.json():null).then(d=>setSupporters(d?.supporters||[])).catch(()=>{});const p=new URLSearchParams(window.location.search);const order=p.get("order");if(p.get("phonepe")==="return"&&order){setResult("Verifying your PhonePe payment…");fetch(`${API}/phonepe/status/${encodeURIComponent(order)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.state==="COMPLETED")setResult("Payment completed successfully. Thank you for supporting ConvertFlow! 🎉");else if(["FAILED","CANCELLED","DECLINED","EXPIRED"].includes(d.state))setResult("The PhonePe payment was not completed. You can try again.");else setResult("Payment is still being confirmed. Refresh this page in a moment if needed.")}).catch(()=>setResult("We could not verify the payment yet. Please refresh this page and try again."))}},[]);
 async function donate(){const clean=name.trim();const value=Number(amount);if(!clean){setError("Enter your name.");return}if(!Number.isFinite(value)||value<1||value>100000){setError("Enter a donation amount between ₹1 and ₹100,000.");return}setBusy(true);setError("");setResult("");try{const r=await fetch(`${API}/phonepe/create`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:clean,amount:value})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||"Could not start PhonePe payment.");localStorage.setItem("convertflow_donor_name",clean);window.location.assign(d.redirectUrl)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="app"><Header/><main className="donate-page"><section className="donate-hero"><div className="donate-copy"><span className="section-label">KEEP CONVERTFLOW FREE</span><h1>Support the tools you use.</h1><p>ConvertFlow is free to use. Your support helps cover infrastructure and add more conversion formats.</p><div className="donate-benefits"><span>✓ Free conversions stay free</span><span>✓ More formats and improvements</span><span>✓ No subscription required</span></div><label htmlFor="donor-name">Your name</label><input id="donor-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" maxLength={80}/><label htmlFor="donation-amount" style={{marginTop:14}}>Donation amount</label><div className="donate-amounts" aria-label="Donation amount presets">{AMOUNTS.map(v=><button type="button" key={v} className={Number(amount)===v?"active":""} onClick={()=>setAmount(String(v))}>₹{v}</button>)}</div><input id="donation-amount" type="number" min="1" max="100000" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Custom amount"/><button className="auth-submit" type="button" onClick={donate} disabled={busy||!name.trim()}>{busy?"Opening PhonePe…":"Pay securely with PhonePe"}</button>{result&&<p className="donate-note">{result}</p>}{error&&<p className="donate-note" style={{color:"#f87171"}}>{error}</p>}<p className="donate-note">Payment is handled securely by PhonePe. ConvertFlow does not display your UPI ID or QR code, and your name is not included in the payment request sent by ConvertFlow.</p></div><aside className="donate-qr-card"><span className="section-label">OUR SUPPORTERS</span>{supporters.length?<div style={{display:"grid",gap:8,marginTop:16}}>{supporters.map(s=><div key={s.id} style={{padding:"10px 12px",borderRadius:12,background:"rgba(255,255,255,.04)",border:"1px solid rgba(148,163,184,.12)",fontWeight:700}}>{s.name}</div>)}</div>:<p>No supporters added yet. Be the first to support ConvertFlow.</p>}<div style={{marginTop:22,paddingTop:18,borderTop:"1px solid rgba(148,163,184,.12)"}}><h2>Thank you ❤️</h2><p>After a successful PhonePe payment is confirmed, your name enters the existing donation review queue for the admin to approve.</p></div></aside></section></main><Footer/></div>}
