import { useEffect,useState } from "react";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Converter from "../components/Converter";
import PopularConversions from "../components/PopularConversions";
import SecuritySection from "../components/SecuritySection";
import Footer from "../components/Footer";
import { Link } from "react-router-dom";
const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
export default function Home(){const[downloadEnabled,setDownloadEnabled]=useState(true);useEffect(()=>{let live=true;fetch(`${API}/site-config`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(live)setDownloadEnabled(d.downloadSectionEnabled!==false)}).catch(()=>{if(live)setDownloadEnabled(true)});return()=>{live=false}},[]);return <div className="app"><Header/><main><Hero/><div id="converter"><Converter/></div><PopularConversions/>{downloadEnabled&&<section className="seo-section cf-download-section"><span className="section-label">CONVERTFLOW APP</span><h2>Download ConvertFlow</h2><p>Use ConvertFlow as a desktop or mobile app. Your device is detected automatically, and you can also choose your platform manually.</p><Link className="auth-submit" style={{display:"inline-flex",marginTop:30,width:"auto"}} to="/download">Download ConvertFlow</Link></section>}<section className="seo-section"><span className="section-label">WHY CONVERTFLOW</span><h2>Free online file conversion without an account</h2><p>Convert common image, video, and audio formats from one simple browser-based tool. No sign-up wall and no subscription required for basic conversions.</p><div className="trust-grid"><article><strong>Simple</strong><span>Clear upload and conversion flow.</span></article><article><strong>Mobile ready</strong><span>Use ConvertFlow on phones, tablets, and desktops.</span></article><article><strong>Privacy minded</strong><span>Temporary conversion files are cleaned automatically.</span></article></div></section><SecuritySection/><section className="seo-section feedback-section"><span className="section-label">CUSTOMER REVIEWS</span><h2>Share your ConvertFlow experience</h2><p>Tell us about speed, formats, reliability, or the interface. Your feedback helps improve ConvertFlow.</p><Link className="auth-submit" style={{display:"inline-flex",marginTop:30,width:"auto"}} to="/contact">Send feedback</Link></section><section className="seo-section"><span className="section-label">POPULAR TOOLS</span><div className="internal-links" style={{marginTop:28}}><Link to="/services/image">Image converter</Link><Link to="/services/video">Video converter</Link><Link to="/services/audio">Audio converter</Link><Link to="/faq">Conversion FAQ</Link></div></section><section className="seo-section"><span className="section-label">MORE</span><div className="internal-links" style={{marginTop:28}}><Link to="/formats">Supported formats</Link><Link to="/history">Recent conversions</Link><Link to="/status">System status</Link><Link to="/api/docs">API documentation</Link></div></section></main><Footer/></div>}