import { useRef, useState } from "react";
import { Archive, ArrowRight, CheckCircle2, Film, Gauge, Image as ImageIcon, Layers3, Sparkles, Upload, Video, WandSparkles, X } from "lucide-react";
import Header from "../components/Header";
import Footer from "../components/Footer";

const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const TOOLS=[
 {id:"crop",title:"Smart Image Crop",desc:"Crop images with precise dimensions and positioning.",icon:ImageIcon,tag:"IMAGE"},
 {id:"compress",title:"Video Compressor",desc:"Shrink MP4 videos while keeping a strong balance of quality and size.",icon:Gauge,tag:"VIDEO"},
 {id:"thumbnail",title:"Video Thumbnail",desc:"Extract a clean frame from any supported video.",icon:Film,tag:"VIDEO"},
 {id:"gif",title:"GIF Maker",desc:"Turn a video clip into a lightweight animated GIF.",icon:WandSparkles,tag:"ANIMATION"},
 {id:"archive",title:"ZIP Creator",desc:"Bundle multiple files into one downloadable ZIP.",icon:Archive,tag:"FILES"}
];
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
async function run(path,form){const r=await fetch(`${API}${path}`,{method:"POST",body:form});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||`Request failed (${r.status})`)}return r.blob();}
export default function Tools(){
 const [tool,setTool]=useState(null),[file,setFile]=useState(null),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[quality,setQuality]=useState("medium"),[resolution,setResolution]=useState("original"),[time,setTime]=useState("1"),[fps,setFps]=useState("12"),[crop,setCrop]=useState({width:"800",height:"600",x:"0",y:"0"});
 const inputRef=useRef(null); const selected=TOOLS.find(x=>x.id===tool);
 const choose=e=>{const list=[...e.target.files];if(tool==="archive")setFiles(list);else setFile(list[0]||null);setMessage("")};
 async function process(){setMessage("");if(tool==="archive"){if(!files.length)return setMessage("Add at least one file to create your ZIP.");const f=new FormData();files.forEach(x=>f.append("files",x));setBusy(true);try{downloadBlob(await run("/tools/archive/zip",f),"convertflow-files.zip");setMessage("ZIP created successfully.")}catch(e){setMessage(e.message)}finally{setBusy(false)}return}if(!file)return setMessage("Choose a file first.");const f=new FormData();f.append("file",file);let endpoint="",name="";const base=file.name.replace(/\.[^.]+$/i,"");if(tool==="crop"){endpoint="/tools/image-crop";Object.entries(crop).forEach(([k,v])=>f.append(k,v));name=`${base}-cropped.png`}if(tool==="compress"){endpoint="/tools/video-compress";f.append("quality",quality);f.append("resolution",resolution);name=`${base}-compressed.mp4`}if(tool==="thumbnail"){endpoint="/tools/video-thumbnail";f.append("time",time);name=`${base}-thumbnail.jpg`}if(tool==="gif"){endpoint="/tools/gif";f.append("fps",fps);name=`${base}.gif`}setBusy(true);try{downloadBlob(await run(endpoint,f),name);setMessage("Done. Your file is ready to download.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <div className="app tools-page"><Header/><main className="tools-shell">
   <section className="tools-hero"><div><span className="section-label">CONVERTFLOW LABS</span><h1>Powerful tools for<br/><span>your files.</span></h1><p>Go beyond basic conversion. Compress, crop, extract, animate and package your files in one polished workspace.</p><div className="tools-hero-meta"><span><CheckCircle2 size={15}/> No account required</span><span><CheckCircle2 size={15}/> Temporary processing</span><span><CheckCircle2 size={15}/> Fast downloads</span></div></div><div className="tools-orb"><div className="orb-ring ring-a"/><div className="orb-ring ring-b"/><Sparkles size={34}/><small>CF LABS</small></div></section>
   <section className="tools-section"><div className="tools-section-head"><div><span className="section-label">ADVANCED TOOLKIT</span><h2>Pick a tool and get to work</h2></div><p>{TOOLS.length} tools available</p></div>
    <div className="tools-grid">{TOOLS.map(({id,title,desc,icon:Icon,tag})=><button key={id} className={`tool-card ${tool===id?"active":""}`} onClick={()=>{setTool(id);setMessage("");setFile(null);setFiles([])}}><div className="tool-card-top"><span className="tool-icon"><Icon size={22}/></span><span className="tool-tag">{tag}</span></div><h3>{title}</h3><p>{desc}</p><span className="tool-open">Open tool <ArrowRight size={15}/></span></button>)}</div>
   </section>
   {selected&&<section className="tool-workspace"><div className="workspace-head"><div><span className="section-label">WORKSPACE</span><h2>{selected.title}</h2><p>{selected.desc}</p></div><button className="workspace-close" onClick={()=>setTool(null)} aria-label="Close"><X size={18}/></button></div><div className="workspace-body">
      <div className="workspace-upload" onClick={()=>inputRef.current?.click()}><input ref={inputRef} hidden type="file" multiple={tool==="archive"} accept={tool==="crop"?"image/*":tool==="compress"||tool==="thumbnail"||tool==="gif"?"video/*":"*/*"} onChange={choose}/><div className="upload-circle"><Upload size={25}/></div><h3>{tool==="archive"?"Drop files here or browse":"Drop your file here or browse"}</h3><p>{tool==="archive"?"Select multiple files to package them into one ZIP.":"Your file is processed temporarily and returned as a download."}</p><span className="workspace-browse">Choose {tool==="archive"?"files":"file"}</span></div>
      {(file||files.length>0)&&<div className="selected-file"><Layers3 size={18}/><div><strong>{tool==="archive"?`${files.length} file${files.length===1?"":"s"} selected`:file.name}</strong><span>{tool==="archive"?"Ready to package":"Ready to process"}</span></div></div>}
      {tool==="crop"&&<div className="tool-options"><label>Width<input value={crop.width} onChange={e=>setCrop(c=>({...c,width:e.target.value}))}/></label><label>Height<input value={crop.height} onChange={e=>setCrop(c=>({...c,height:e.target.value}))}/></label><label>X position<input value={crop.x} onChange={e=>setCrop(c=>({...c,x:e.target.value}))}/></label><label>Y position<input value={crop.y} onChange={e=>setCrop(c=>({...c,y:e.target.value}))}/></label></div>}
      {tool==="compress"&&<div className="tool-options"><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>original</option><option>1080p</option><option>720p</option><option>480p</option></select></label></div>}
      {tool==="thumbnail"&&<label className="single-option">Timestamp in seconds<input value={time} onChange={e=>setTime(e.target.value)} type="number" min="0" step="0.5"/></label>}
      {tool==="gif"&&<label className="single-option">Frames per second<input value={fps} onChange={e=>setFps(e.target.value)} type="number" min="1" max="30"/></label>}
      <div className="workspace-action"><button className="lab-primary" disabled={busy} onClick={process}>{busy?<><span className="spinner"/>Processing...</>:<>Process with ConvertFlow <ArrowRight size={17}/></>}</button>{message&&<p className={message.startsWith("Done")||message.includes("successfully")?"success-msg":"error-msg"} role="status">{message}</p>}</div>
   </div></section>}
   {!tool&&<section className="tools-bottom"><div><span className="section-label">BUILT FOR REAL WORK</span><h2>Simple on the surface. Powerful underneath.</h2></div><div className="tool-trust"><article><Gauge/><strong>Fast processing</strong><span>Optimized backend workflows for common media tasks.</span></article><article><Layers3/><strong>One workspace</strong><span>Move between tools without leaving ConvertFlow.</span></article><article><CheckCircle2/><strong>Privacy minded</strong><span>Temporary files are cleaned after processing.</span></article></div></section>}
 </main><Footer/></div>
}