import { useRef, useState } from "react";
import { ArrowRight, Archive, AudioWaveform, CheckCircle2, Expand, Film, Gauge, Image as ImageIcon, Layers3, Maximize2, Play, Scissors, Sparkles, Stamp, Upload, VolumeX, WandSparkles, X } from "lucide-react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./tools.css";

const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const TOOLS=[
{id:"crop",title:"Smart Image Crop",desc:"Crop images with precise dimensions and positioning.",icon:ImageIcon,tag:"IMAGE",endpoint:"/tools/image-crop"},
{id:"bg",title:"Background Remover",desc:"Remove simple image backgrounds and export transparent PNG.",icon:Scissors,tag:"IMAGE",endpoint:"/tools/image-background-remover"},
{id:"watermark",title:"Watermark Studio",desc:"Add a clean text watermark to your images.",icon:Stamp,tag:"IMAGE",endpoint:"/tools/image-watermark"},
{id:"enhance",title:"Image Enhancer",desc:"Improve levels and sharpness for a cleaner image.",icon:Sparkles,tag:"IMAGE",endpoint:"/tools/image-enhance"},
{id:"upscale",title:"Image Upscaler",desc:"Resize images from 144p up to 8K with high-quality Lanczos scaling.",icon:Expand,tag:"IMAGE",endpoint:"/tools/image-upscale"},
{id:"compress",title:"Video Compressor",desc:"Shrink MP4 videos while keeping a strong quality balance.",icon:Gauge,tag:"VIDEO",endpoint:"/tools/video-compress"},
{id:"resolution",title:"Video Resolution",desc:"Convert videos to 480p, 720p, 1080p, 1440p or 4K.",icon:Maximize2,tag:"VIDEO",endpoint:"/tools/video-resolution"},
{id:"fps",title:"Frame Rate Converter",desc:"Convert video frame rate from 1 to 120 FPS.",icon:Film,tag:"VIDEO",endpoint:"/tools/video-framerate"},
{id:"mute",title:"Remove Video Audio",desc:"Create a clean silent copy of your video.",icon:VolumeX,tag:"VIDEO",endpoint:"/tools/video-mute"},
{id:"speed",title:"Video Speed",desc:"Slow down or speed up video from 0.25x to 4x.",icon:Play,tag:"VIDEO",endpoint:"/tools/video-speed"},
{id:"thumbnail",title:"Video Thumbnail",desc:"Extract a clean frame from any supported video.",icon:Film,tag:"VIDEO",endpoint:"/tools/video-thumbnail"},
{id:"gif",title:"GIF Maker",desc:"Turn a video clip into an animated GIF.",icon:WandSparkles,tag:"ANIMATION",endpoint:"/tools/gif"},
{id:"fade",title:"Audio Fade",desc:"Add smooth fade-in and fade-out to audio.",icon:VolumeX,tag:"AUDIO",endpoint:"/tools/audio-fade"},
{id:"waveform",title:"Audio Waveform",desc:"Turn audio into a downloadable visual waveform.",icon:AudioWaveform,tag:"AUDIO",endpoint:"/tools/audio-waveform"},
{id:"archive",title:"ZIP Creator",desc:"Bundle multiple files into one downloadable ZIP.",icon:Archive,tag:"FILES",endpoint:"/tools/archive/zip"}
];
const imageTools=new Set(["crop","bg","watermark","enhance","upscale"]),videoTools=new Set(["compress","resolution","fps","mute","speed","thumbnail","gif"]),audioTools=new Set(["fade","waveform"]);
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function requestWithProgress(endpoint,form,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`${API}${endpoint}`);xhr.responseType="blob";xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.min(70,Math.round((e.loaded/e.total)*70)),"Uploading")};xhr.upload.onload=()=>onProgress(70,"Processing");xhr.onprogress=()=>onProgress(88,"Finalizing");xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)return resolve(xhr.response);try{const text=new TextDecoder().decode(xhr.response);const data=JSON.parse(text);reject(new Error(data.message||`Request failed (${xhr.status})`))}catch{reject(new Error(`Request failed (${xhr.status})`))}};xhr.onerror=()=>reject(new Error("Network error. Please try again."));xhr.send(form)})}

export default function Tools(){
const[toolId,setToolId]=useState(null),[file,setFile]=useState(null),[files,setFiles]=useState([]),[previewUrl,setPreviewUrl]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[progress,setProgress]=useState(0),[progressLabel,setProgressLabel]=useState("Ready");
const[quality,setQuality]=useState("medium"),[resolution,setResolution]=useState("original"),[fps,setFps]=useState("30"),[speed,setSpeed]=useState("1"),[time,setTime]=useState("1"),[fade,setFade]=useState("3"),[upscale,setUpscale]=useState("4k"),[watermark,setWatermark]=useState("ConvertFlow"),[crop,setCrop]=useState({width:"800",height:"600",x:"0",y:"0"});
const inputRef=useRef(null),selected=TOOLS.find(tool=>tool.id===toolId);
function clearPreview(){if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl("")}
function openTool(id){clearPreview();setToolId(id);setFile(null);setFiles([]);setMessage("");setProgress(0);setTimeout(()=>document.querySelector(".tool-workspace")?.scrollIntoView({behavior:"smooth",block:"start"}),50)}
function setSelected(next){if(!next)return;setFile(next);clearPreview();if(next.type.startsWith("image/"))setPreviewUrl(URL.createObjectURL(next));setMessage("");setProgress(0)}
function chooseFiles(e){const picked=Array.from(e.target.files||[]);if(toolId==="archive")setFiles(picked);else setSelected(picked[0]);e.target.value=""}
function dropFiles(e){e.preventDefault();const picked=Array.from(e.dataTransfer.files||[]);if(!picked.length)return;if(toolId==="archive")setFiles(picked);else setSelected(picked[0])}
async function processTool(){setMessage("");if(toolId==="archive"){if(!files.length)return setMessage("Add at least one file first.");const form=new FormData();files.forEach(item=>form.append("files",item));setBusy(true);setProgress(0);setProgressLabel("Uploading");try{downloadBlob(await requestWithProgress(selected.endpoint,form,(p,l)=>{setProgress(p);setProgressLabel(l)}),"convertflow-files.zip");setProgress(100);setProgressLabel("Complete");setMessage("ZIP created successfully.")}catch(e){setMessage(e.message)}finally{setBusy(false)}return}if(!file)return setMessage("Choose a file first.");const form=new FormData();form.append("file",file);const base=file.name.replace(/\.[^.]+$/i,"");let output=`${base}-converted`;
if(toolId==="crop"){Object.entries(crop).forEach(([k,v])=>form.append(k,v));output=`${base}-cropped.png`}else if(toolId==="watermark"){form.append("text",watermark);output=`${base}-watermarked.png`}else if(toolId==="upscale"){form.append("quality",upscale);output=`${base}-${upscale}.jpg`}else if(toolId==="compress"){form.append("quality",quality);form.append("resolution",resolution);output=`${base}-compressed.mp4`}else if(toolId==="resolution"){form.append("resolution",resolution);output=`${base}-${resolution}.mp4`}else if(toolId==="fps"){form.append("fps",fps);output=`${base}-${fps}fps.mp4`}else if(toolId==="speed"){form.append("speed",speed);output=`${base}-${speed}x.mp4`}else if(toolId==="thumbnail"){form.append("time",time);output=`${base}-thumbnail.jpg`}else if(toolId==="gif"){form.append("fps",fps);output=`${base}.gif`}else if(toolId==="fade"){form.append("fade",fade);output=`${base}-fade.mp3`}else if(toolId==="waveform"){output=`${base}-waveform.png`}else if(toolId==="bg"){output=`${base}-no-background.png`}else if(toolId==="enhance"){output=`${base}-enhanced.png`}else if(toolId==="mute"){output=`${base}-muted.mp4`}
setBusy(true);setProgress(0);setProgressLabel("Uploading");try{downloadBlob(await requestWithProgress(selected.endpoint,form,(p,l)=>{setProgress(p);setProgressLabel(l)}),output);setProgress(100);setProgressLabel("Complete");setMessage("Done. Your file is ready to download.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}
const accept=imageTools.has(toolId)?"image/*":videoTools.has(toolId)?"video/*":audioTools.has(toolId)?"audio/*":"*/*";
return <div className="app tools-page"><Header/><main className="tools-shell"><section className="tools-hero"><div><span className="section-label">CONVERTFLOW LABS</span><h1>Powerful tools for<br/><span>your files.</span></h1><p>Edit, enhance, compress, animate and package your files in one polished workspace.</p><div className="tools-hero-meta"><span><CheckCircle2 size={15}/> No account required</span><span><CheckCircle2 size={15}/> Temporary processing</span><span><CheckCircle2 size={15}/> Fast downloads</span></div></div><div className="tools-orb"><div className="orb-ring ring-a"/><div className="orb-ring ring-b"/><Sparkles size={34}/><small>CF LABS</small></div></section>
<section className="tools-section"><div className="tools-section-head"><div><span className="section-label">ADVANCED TOOLKIT</span><h2>Pick a tool and get to work</h2></div><p>{TOOLS.length} tools available</p></div><div className="tools-grid">{TOOLS.map(({id,title,desc,icon:Icon,tag})=><button type="button" key={id} className={`tool-card ${toolId===id?"active":""}`} onClick={()=>openTool(id)}><div className="tool-card-top"><span className="tool-icon"><Icon size={22}/></span><span className="tool-tag">{tag}</span></div><h3>{title}</h3><p>{desc}</p><span className="tool-open">Open tool <ArrowRight size={15}/></span></button>)}</div></section>
{selected&&<section className="tool-workspace"><div className="workspace-head"><div><span className="section-label">WORKSPACE</span><h2>{selected.title}</h2><p>{selected.desc}</p></div><button type="button" className="workspace-close" onClick={()=>setToolId(null)} aria-label="Close"><X size={18}/></button></div><div className="workspace-body"><div className="workspace-upload" onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={dropFiles}><input ref={inputRef} hidden type="file" multiple={toolId==="archive"} accept={accept} onChange={chooseFiles}/><div className="upload-circle"><Upload size={25}/></div><h3>{toolId==="archive"?"Drop files here or browse":"Drop your file here or browse"}</h3><p>Drag and drop works too. Your file is processed temporarily.</p><span className="workspace-browse">Choose {toolId==="archive"?"files":"file"}</span></div>
{(file||files.length)>0&&<div className="selected-file"><Layers3 size={18}/><div><strong>{toolId==="archive"?`${files.length} files selected`:file.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · Ready to process`:"Ready to process"}</span></div></div>}
{previewUrl&&imageTools.has(toolId)&&<div className="image-preview-card"><div className="image-preview-head"><strong>Image preview</strong><span>{file?.type||"image"}</span></div><div className="image-preview-frame"><img src={previewUrl} alt="Selected image preview"/></div></div>}
{toolId==="crop"&&<div className="tool-options">{[["Width","width"],["Height","height"],["X position","x"],["Y position","y"]].map(([label,key])=><label key={key}>{label}<input value={crop[key]} onChange={e=>setCrop(c=>({...c,[key]:e.target.value}))}/></label>)}</div>}
{toolId==="watermark"&&<label className="single-option">Watermark text<input value={watermark} onChange={e=>setWatermark(e.target.value)} maxLength="100"/></label>}
{toolId==="upscale"&&<div className="upscale-picker"><div className="option-heading"><span>Target resolution</span><small>Choose the output size</small></div><div className="upscale-options">{[["144p","256×144"],["240p","426×240"],["360p","640×360"],["480p","854×480"],["720p","1280×720"],["1080p","1920×1080"],["1440p","2560×1440"],["2k","2560×1440"],["4k","3840×2160"],["5k","5120×2880"],["6k","6144×3456"],["8k","7680×4320"]].map(([value,size])=><button type="button" key={value} className={`upscale-option ${upscale===value?"selected":""}`} onClick={()=>setUpscale(value)}><strong>{value.toUpperCase()}</strong><span>{size}</span>{upscale===value&&<CheckCircle2 size={16}/>}</button>)}</div></div>}
{toolId==="compress"&&<div className="tool-options"><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>original</option><option>1080p</option><option>720p</option><option>480p</option></select></label></div>}
{toolId==="resolution"&&<label className="single-option">Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>480p</option><option>720p</option><option>1080p</option><option>1440p</option><option>4k</option></select></label>}
{toolId==="fps"&&<label className="single-option">Target FPS<input type="number" min="1" max="120" value={fps} onChange={e=>setFps(e.target.value)}/></label>}{toolId==="speed"&&<label className="single-option">Playback speed<select value={speed} onChange={e=>setSpeed(e.target.value)}><option value="0.25">0.25x</option><option value="0.5">0.5x</option><option value="1">1x</option><option value="1.5">1.5x</option><option value="2">2x</option><option value="4">4x</option></select></label>}{toolId==="thumbnail"&&<label className="single-option">Timestamp in seconds<input type="number" min="0" step="0.5" value={time} onChange={e=>setTime(e.target.value)}/></label>}{toolId==="gif"&&<label className="single-option">Frames per second<input type="number" min="1" max="30" value={fps} onChange={e=>setFps(e.target.value)}/></label>}{toolId==="fade"&&<label className="single-option">Fade duration in seconds<input type="number" min="0.1" max="30" step="0.5" value={fade} onChange={e=>setFade(e.target.value)}/></label>}
{busy&&<div className="progress-panel"><div className="progress-top"><strong>{progressLabel}</strong><span>{progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${Math.max(4,progress)}%`}}/></div><small>{progressLabel==="Uploading"?"Sending your file securely...":progressLabel==="Processing"?"ConvertFlow is processing your file...":"Preparing your download..."}</small></div>}
<div className="workspace-action"><button type="button" className="lab-primary" disabled={busy} onClick={processTool}>{busy?<><span className="spinner"/> {progressLabel}...</>:<>Process with ConvertFlow <ArrowRight size={17}/></>}</button>{message&&<p className={message.startsWith("Done")||message.includes("successfully")?"success-msg":"error-msg"} role="status">{message}</p>}</div></div></section>}
{!toolId&&<section className="tools-bottom"><div><span className="section-label">BUILT FOR REAL WORK</span><h2>Simple on the surface. Powerful underneath.</h2></div><div className="tool-trust"><article><Gauge/><strong>Fast processing</strong><span>Optimized backend workflows for common media tasks.</span></article><article><Layers3/><strong>One workspace</strong><span>Move between tools without leaving ConvertFlow.</span></article><article><CheckCircle2/><strong>Privacy minded</strong><span>Temporary files are cleaned after processing.</span></article></div></section>}</main><Footer/></div>;
}
