import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, Download, FileImage, FileVideo, Gauge, Heart, History, Maximize2, Search, ShieldCheck, Sparkles, Upload, X } from "lucide-react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./toolsEnhanced.css";

const API=(import.meta.env.VITE_API_URL||"https://convertflow-backend.onrender.com/api").replace(/\/$/,"");
const TOOLS=[
 ["crop","Smart Image Crop","Crop images with precise dimensions.",FileImage,"IMAGE","/tools/image-crop"],
 ["optimize","Smart Image Compressor","Reduce image size while keeping quality.",Gauge,"IMAGE","/tools/image-optimize"],
 ["metadata","Remove Image Metadata","Strip EXIF and hidden image metadata.",ShieldCheck,"PRIVACY","/tools/image-metadata-remove"],
 ["convert","Image Format Converter","Convert JPG, PNG, WebP or AVIF.",FileImage,"IMAGE","/tools/image-convert"],
 ["resize","Image Resizer","Resize with optional aspect-ratio protection.",Maximize2,"IMAGE","/tools/image-resize"],
 ["adjust","Image Color Studio","Tune brightness, contrast, saturation and sharpness.",Sparkles,"IMAGE","/tools/image-adjust"],
 ["bg","Background Remover","Remove simple image backgrounds.",Sparkles,"IMAGE","/tools/image-background-remover"],
 ["watermark","Watermark Studio","Add a clean text watermark.",Sparkles,"IMAGE","/tools/image-watermark"],
 ["enhance","Image Enhancer","Improve levels and sharpness.",Sparkles,"IMAGE","/tools/image-enhance"],
 ["upscale","Image Upscaler","Upscale from 144p to 8K.",Maximize2,"IMAGE","/tools/image-upscale"],
 ["compress","Video Compressor","Shrink MP4 while controlling quality.",Gauge,"VIDEO","/tools/video-compress"],
 ["resolution","Video Resolution","Convert to 480p through 4K.",Maximize2,"VIDEO","/tools/video-resolution"],
 ["fps","Frame Rate Converter","Convert video from 1 to 120 FPS.",FileVideo,"VIDEO","/tools/video-framerate"],
 ["mute","Remove Video Audio","Create a silent copy of your video.",FileVideo,"VIDEO","/tools/video-mute"],
 ["speed","Video Speed","Slow down or speed up video.",FileVideo,"VIDEO","/tools/video-speed"],
 ["thumbnail","Video Thumbnail","Extract a frame from your video.",FileVideo,"VIDEO","/tools/video-thumbnail"],
 ["audio","Extract Audio","Extract MP3, WAV, AAC, FLAC, M4A or OGG.",FileVideo,"AUDIO","/tools/audio-extract"],
 ["gif","GIF Maker","Turn a video into an animated GIF.",Sparkles,"VIDEO","/tools/gif"]
];
const imageIds=new Set(["crop","optimize","metadata","convert","resize","adjust","bg","watermark","enhance","upscale"]);
const videoIds=new Set(["compress","resolution","fps","mute","speed","thumbnail","gif"]);
function size(n){if(!n)return "0 B";const units=["B","KB","MB","GB"];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return `${x.toFixed(i?1:0)} ${units[i]}`}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function request(endpoint,form,onProgress,attempt=0){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`${API}${endpoint}`);xhr.responseType="blob";xhr.upload.onprogress=e=>e.lengthComputable&&onProgress(Math.round(e.loaded/e.total*65),"Uploading");xhr.upload.onload=()=>onProgress(70,"Processing");xhr.onprogress=()=>onProgress(90,"Finalizing");xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)return resolve(xhr.response);let msg=`Request failed (${xhr.status})`;try{msg=JSON.parse(new TextDecoder().decode(xhr.response)).message||msg}catch{}if(attempt<2&&xhr.status>=500)return setTimeout(()=>request(endpoint,form,onProgress,attempt+1).then(resolve).catch(reject),700*(attempt+1));reject(new Error(msg))};xhr.onerror=()=>attempt<2?setTimeout(()=>request(endpoint,form,onProgress,attempt+1).then(resolve).catch(reject),700*(attempt+1)):reject(new Error("Network error. Please try again."));xhr.send(form)})}

export default function ToolsEnhanced(){
 const [active,setActive]=useState(null),[files,setFiles]=useState([]),[preview,setPreview]=useState(""),[query,setQuery]=useState(""),[favorites,setFavorites]=useState(()=>JSON.parse(localStorage.getItem("cf_favorites")||"[]")),[history,setHistory]=useState(()=>JSON.parse(localStorage.getItem("cf_history")||"[]")),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[label,setLabel]=useState("Ready"),[message,setMessage]=useState(""),[stats,setStats]=useState(null),[queue,setQueue]=useState([]);
 const [quality,setQuality]=useState("82"),[format,setFormat]=useState("webp"),[width,setWidth]=useState("1920"),[height,setHeight]=useState("1080"),[keep,setKeep]=useState(true),[brightness,setBrightness]=useState(0),[contrast,setContrast]=useState(0),[saturation,setSaturation]=useState(0),[sharpness,setSharpness]=useState(0),[upscale,setUpscale]=useState("4k"),[resolution,setResolution]=useState("1080p"),[fps,setFps]=useState("30"),[speed,setSpeed]=useState("1"),[time,setTime]=useState("1"),[watermark,setWatermark]=useState("ConvertFlow");
 const input=useRef(null),tool=TOOLS.find(t=>t[0]===active);
 useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview]);
 const filtered=useMemo(()=>TOOLS.filter(t=>`${t[1]} ${t[2]} ${t[4]}`.toLowerCase().includes(query.toLowerCase())),[query]);
 function open(id){if(preview)URL.revokeObjectURL(preview);setActive(id);setFiles([]);setPreview("");setMessage("");setStats(null);setQueue([]);const next=[{id,at:Date.now()},...history.filter(x=>x.id!==id)].slice(0,12);setHistory(next);localStorage.setItem("cf_history",JSON.stringify(next));setTimeout(()=>document.querySelector(".te-workspace")?.scrollIntoView({behavior:"smooth",block:"start"}),60)}
 function favorite(e,id){e.stopPropagation();const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem("cf_favorites",JSON.stringify(next))}
 function pick(e){const f=Array.from(e.target.files||[]);setFiles(f);if(preview)URL.revokeObjectURL(preview);setPreview(f[0]?.type.startsWith("image/")?URL.createObjectURL(f[0]):"");e.target.value=""}
 function drop(e){e.preventDefault();const f=Array.from(e.dataTransfer.files||[]);if(!f.length)return;setFiles(f);if(preview)URL.revokeObjectURL(preview);setPreview(f[0]?.type.startsWith("image/")?URL.createObjectURL(f[0]):"")}
 function formFor(file){const f=new FormData();f.append("file",file);if(active==="optimize"){f.append("quality",quality);f.append("format",format)}if(active==="convert"){f.append("format",format)}if(active==="resize"){f.append("width",width);f.append("height",height);f.append("keepAspect",keep)}if(active==="adjust"){f.append("brightness",brightness);f.append("contrast",contrast);f.append("saturation",saturation);f.append("sharpness",sharpness)}if(active==="crop"){f.append("width",width);f.append("height",height);f.append("x",0);f.append("y",0)}if(active==="watermark")f.append("text",watermark);if(active==="upscale")f.append("quality",upscale);if(active==="compress"){f.append("quality","medium");f.append("resolution",resolution)}if(active==="resolution")f.append("resolution",resolution);if(active==="fps")f.append("fps",fps);if(active==="speed")f.append("speed",speed);if(active==="thumbnail")f.append("time",time);if(active==="gif")f.append("fps",fps);if(active==="audio")f.append("format",format);return f}
 function name(file){const b=file.name.replace(/\.[^.]+$/i,"");const ext={optimize:format,convert:format,resize:"png",adjust:"png",crop:"png",metadata:"png",bg:"png",watermark:"png",enhance:"png",upscale:"png",compress:"mp4",resolution:"mp4",fps:"mp4",mute:"mp4",speed:"mp4",thumbnail:"jpg",gif:"gif",audio:format}[active]||"bin";return `${b}-convertflow.${ext}`}
 async function process(){if(!tool)return;if(!files.length){setMessage("Choose at least one file first.");return}setBusy(true);setMessage("");setStats(null);setQueue(files.map(f=>({name:f.name,status:"Waiting",progress:0})));try{for(let i=0;i<files.length;i++){const file=files[i];setQueue(q=>q.map((x,j)=>j===i?{...x,status:"Uploading",progress:0}:x));const before=file.size;const blob=await request(tool[5],formFor(file),(p,l)=>{setProgress(p);setLabel(`${l} · ${i+1}/${files.length}`);setQueue(q=>q.map((x,j)=>j===i?{...x,status:l,progress:p}:x))});download(blob,name(file));setQueue(q=>q.map((x,j)=>j===i?{...x,status:"Complete",progress:100}:x));setStats({before,after:blob.size})}setProgress(100);setLabel("Complete");setMessage(`${files.length} file${files.length>1?"s":""} processed successfully.`)}catch(e){setMessage(e.message);setQueue(q=>q.map(x=>x.status==="Complete"?x:{...x,status:"Failed"}))}finally{setBusy(false)}}
 const accept=imageIds.has(active)?"image/*":videoIds.has(active)?"video/*":active==="audio"?"video/*,audio/*":"*/*";
 return <div className="app tools-enhanced"><Header/><main className="te-shell"><section className="te-hero"><div><span className="section-label">CONVERTFLOW LABS</span><h1>Everything your files need.</h1><p>Convert, compress, enhance, resize and process files in one fast workspace.</p><div className="te-meta"><span><CheckCircle2 size={15}/> No account</span><span><ShieldCheck size={15}/> Temporary processing</span><span><Clock3 size={15}/> Automatic cleanup</span></div></div><div className="te-hero-card"><Sparkles size={30}/><strong>{TOOLS.length} tools</strong><span>One workspace</span></div></section>
 <section className="te-tools"><div className="te-heading"><div><span className="section-label">TOOLKIT</span><h2>Pick a tool</h2></div><span>{filtered.length} results</span></div><div className="te-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools..."/></div>{favorites.length>0&&<div className="te-favorites"><Heart size={15} fill="currentColor"/><strong>Favorites</strong>{favorites.map(id=>{const t=TOOLS.find(x=>x[0]===id);return t?<button key={id} onClick={()=>open(id)}>{t[1]}</button>:null})}</div>}<div className="te-grid">{filtered.map(([id,title,desc,Icon,tag])=><button className={`te-card ${active===id?"active":""}`} key={id} onClick={()=>open(id)}><div className="te-card-top"><span className="te-icon"><Icon size={20}/></span><div><span>{tag}</span><button className="te-heart" onClick={e=>favorite(e,id)}>{favorites.includes(id)?"♥":"♡"}</button></div></div><h3>{title}</h3><p>{desc}</p><b>Open <ArrowRight size={14}/></b></button>)}</div></section>
 {history.length>0&&!active&&<section className="te-history"><div className="te-history-head"><span><History size={17}/> Recently used</span><button onClick={()=>{setHistory([]);localStorage.removeItem("cf_history")}}>Clear</button></div><div>{history.slice(0,6).map(h=>{const t=TOOLS.find(x=>x[0]===h.id);return t?<button key={h.id} onClick={()=>open(h.id)}>{t[1]}<small>{new Date(h.at).toLocaleDateString()}</small></button>:null})}</div></section>}
 {tool&&<section className="te-workspace"><div className="te-work-head"><div><span className="section-label">WORKSPACE</span><h2>{tool[1]}</h2><p>{tool[2]}</p></div><button onClick={()=>setActive(null)}><X size={18}/></button></div><div className="te-work-body"><div className="te-privacy"><ShieldCheck size={18}/><div><strong>Your files stay temporary</strong><span>Files are processed and automatically cleaned after the operation.</span></div></div><div className="te-drop" onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("over")}} onDragLeave={e=>e.currentTarget.classList.remove("over")} onDrop={e=>{e.currentTarget.classList.remove("over");drop(e)}}><input ref={input} hidden type="file" multiple accept={accept} onChange={pick}/><Upload size={25}/><strong>Drop files here or browse</strong><span>{files.length>1?`${files.length} files selected`:"Multiple files are supported"}</span><b>Choose files</b></div>{files.length>0&&<div className="te-selected"><strong>{files.length===1?files[0].name:`${files.length} files in queue`}</strong><span>{files.length===1?size(files[0].size):"Processed one by one"}</span></div>}{preview&&<div className="te-preview"><div><strong>Image preview</strong><span>Limited preview</span></div><img src={preview} alt="Preview"/></div>}
 {active==="optimize"&&<div className="te-options"><label>Quality<input type="number" min="20" max="100" value={quality} onChange={e=>setQuality(e.target.value)}/></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option>webp</option><option>jpg</option><option>png</option><option>avif</option></select></label></div>}
 {active==="convert"&&<label className="te-single">Output format<select value={format} onChange={e=>setFormat(e.target.value)}><option>webp</option><option>jpg</option><option>png</option><option>avif</option></select></label>}
 {active==="resize"&&<div className="te-options"><label>Width<input type="number" value={width} onChange={e=>setWidth(e.target.value)}/></label><label>Height<input type="number" value={height} onChange={e=>setHeight(e.target.value)}/></label><label className="te-check"><input type="checkbox" checked={keep} onChange={e=>setKeep(e.target.checked)}/> Keep aspect ratio</label></div>}
 {active==="adjust"&&<div className="te-sliders">{[["Brightness",brightness,setBrightness,-100,100],["Contrast",contrast,setContrast,-100,100],["Saturation",saturation,setSaturation,-100,100],["Sharpness",sharpness,setSharpness,0,5]].map(([n,v,s,min,max])=><label key={n}>{n}<input type="range" min={min} max={max} step={max===5?.1:1} value={v} onChange={e=>s(e.target.value)}/><span>{v}</span></label>)}</div>}
 {active==="watermark"&&<label className="te-single">Watermark text<input value={watermark} onChange={e=>setWatermark(e.target.value)}/></label>}
 {active==="crop"&&<div className="te-options"><label>Width<input type="number" value={width} onChange={e=>setWidth(e.target.value)}/></label><label>Height<input type="number" value={height} onChange={e=>setHeight(e.target.value)}/></label></div>}
 {active==="upscale"&&<div className="te-resolution"><div><strong>Target resolution</strong><span>Choose your output quality</span></div><div>{[["144p","256×144"],["240p","426×240"],["360p","640×360"],["480p","854×480"],["720p","1280×720"],["1080p","1920×1080"],["1440p","2560×1440"],["2k","2560×1440"],["4k","3840×2160"],["5k","5120×2880"],["6k","6144×3456"],["8k","7680×4320"]].map(([v,s])=><button className={upscale===v?"selected":""} key={v} onClick={()=>setUpscale(v)}><strong>{v.toUpperCase()}</strong><span>{s}</span>{upscale===v&&<CheckCircle2 size={15}/>}</button>)}</div></div>}
 {active==="compress"&&<label className="te-single">Target resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>original</option><option>1080p</option><option>720p</option><option>480p</option></select></label>}
 {active==="resolution"&&<label className="te-single">Target resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>480p</option><option>720p</option><option>1080p</option><option>1440p</option><option>4k</option></select></label>}
 {active==="fps"&&<label className="te-single">Target FPS<input type="number" min="1" max="120" value={fps} onChange={e=>setFps(e.target.value)}/></label>}{active==="speed"&&<label className="te-single">Playback speed<select value={speed} onChange={e=>setSpeed(e.target.value)}><option>0.25</option><option>0.5</option><option>1</option><option>1.5</option><option>2</option><option>4</option></select></label>}{active==="thumbnail"&&<label className="te-single">Timestamp<input type="number" min="0" value={time} onChange={e=>setTime(e.target.value)}/></label>}{active==="gif"&&<label className="te-single">FPS<input type="number" min="1" max="30" value={fps} onChange={e=>setFps(e.target.value)}/></label>}{active==="audio"&&<label className="te-single">Audio format<select value={format} onChange={e=>setFormat(e.target.value)}><option>mp3</option><option>wav</option><option>aac</option><option>flac</option><option>m4a</option><option>ogg</option></select></label>}
 {queue.length>0&&<div className="te-queue"><div><strong>Conversion queue</strong><span>{queue.filter(q=>q.status==="Complete").length}/{queue.length}</span></div>{queue.map((q,i)=><article key={`${q.name}-${i}`}><span>{q.status==="Complete"?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</span><div><strong>{q.name}</strong><small>{q.status}</small></div><b>{q.progress}%</b></article>)}</div>}
 {stats&&<div className="te-stats"><div><span>Original</span><strong>{size(stats.before)}</strong></div><div><span>Output</span><strong>{size(stats.after)}</strong></div><div><span>Result</span><strong>{stats.after<stats.before?`${Math.round((1-stats.after/stats.before)*100)}% smaller`:"Processed"}</strong></div></div>}
 {busy&&<div className="te-progress"><div><strong>{label}</strong><span>{progress}%</span></div><div><i style={{width:`${Math.max(progress,4)}%`}}/></div><small>Large video files may take longer. Temporary server failures retry automatically.</small></div>}
 <button className="te-process" disabled={busy} onClick={process}>{busy?label:<><Download size={16}/> Process {files.length||0} file{files.length===1?"":"s"}</>}</button>{message&&<p className={message.includes("successfully")?"te-success":"te-error"}>{message}</p>}</div></section>}
 </main><Footer/></div>
}
